# Generated by Django 6.1 on 2026-08-29 09:40

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(upload_to=api.models.generateimage)),
                ('role', models.CharField(choices=[('E', 'Employer'), ('W', 'Worker')], default='W', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
