# Generated by Django 6.1 on 2026-08-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='task_image',
            new_name='project_image',
        ),
    ]
