# Generated by Django 6.1 on 2026-08-29 17:38

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.generate_attachement_path),
        ),
    ]
